apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
#      initContainers:
#      # NOTE:
#      # This is to fix the permission on the volume
#      # By default elasticsearch container is not run as
#      # non root user.
#      # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_notes_for_production_use_and_defaults
#      - name: fix-the-volume-permission
#        image: busybox
#        command:
#        - sh
#        - -c
#        - chown -R postgres:postgres /var/lib/postgresql/data2
#        securityContext:
#          privileged: true
#        volumeMounts:
#        - name: postgres-data
#          mountPath: /var/lib/postgresql/data2
      containers:
      - name: postgres
        image: postgres
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        resources:
          limits:
            memory: "256Mi"
        env:
        - name: POSTGRES_PASSWORD
          value: "SuperSecret"
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-data-claim
---
kind: Service
apiVersion: v1
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
