apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-data-vol
  labels:
    type: local
    app: postgres
spec:
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: local
  hostPath:
    path: '/mnt/d/data/postgres'
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-data-claim
  labels:
    app: postgres
spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
