CREATE TABLE families (id SERIAL PRIMARY KEY, surname TEXT, home_phone TEXT, envelope_number INTEGER, addr_street1 TEXT, addr_street2 TEXT, addr_city TEXT, addr_state TEXT, addr_zip INTEGER, photo_guid TEXT, inactive boolean DEFAULT false);
CREATE TABLE people (id SERIAL PRIMARY KEY, name TEXT, birthdate TIMESTAMP WITH TIME ZONE, email TEXT, phonenumber TEXT, head_of_house boolean, family_id INTEGER, member_since TIMESTAMP WITH TIME ZONE, photo_guid TEXT, inactive boolean DEFAULT false);
CREATE TABLE ministries (id SERIAL PRIMARY KEY, name TEXT, description TEXT);
CREATE TABLE ministry_enrollments (person_id INTEGER REFERENCES people(id) ON DELETE CASCADE, ministry_id INTEGER REFERENCES ministries(id) ON DELETE CASCADE, role TEXT);
CREATE TABLE pledges (id SERIAL PRIMARY KEY, family_id INTEGER REFERENCES families(id), pledge_type TEXT, pledge_date TIMESTAMP WITH TIME ZONE, pledge_start TIMESTAMP WITH TIME ZONE, pledge_end TIMESTAMP WITH TIME ZONE, frequency TEXT, pledge_increment FLOAT, total_pledge FLOAT);
CREATE TABLE donations (id BIGSERIAL PRIMARY KEY, family_id INTEGER REFERENCES families(id), amount FLOAT, date TIMESTAMP WITH TIME ZONE, type TEXT, check_number INTEGER, transaction_id bigint);
CREATE TABLE events (id SERIAL PRIMARY KEY, start_time TIMESTAMP WITH TIME ZONE, recurring_meeting_id INTEGER, end_time TIMESTAMP WITH TIME ZONE, description TEXT, scheduler_id INTEGER REFERENCES people(id) ON DELETE SET NULL, ministry_id INTEGER REFERENCES ministries(id) ON DELETE CASCADE);
CREATE TABLE rooms (id SERIAL PRIMARY KEY, name TEXT, type TEXT, capacity INTEGER);
CREATE TABLE equipment (id SERIAL PRIMARY KEY, name TEXT, manufacturer TEXT, description TEXT);
CREATE TABLE reservations (id BIGSERIAL PRIMARY KEY, resource_type TEXT, resource_id INTEGER, reserving_person_id INTEGER REFERENCES people(id) ON DELETE SET NULL, event_id INTEGER, start_time TIMESTAMP WITH TIME ZONE, end_time TIMESTAMP WITH TIME ZONE);
CREATE TABLE recurrences(id SERIAL PRIMARY KEY, cycle TEXT, frequency INTEGER, end_date TIMESTAMP WITH TIME ZONE, weekly_days INTEGER);
CREATE TABLE roles (id SERIAL PRIMARY KEY, name TEXT);
CREATE TABLE permissions (role_id INTEGER REFERENCES roles(id) ON DELETE CASCADE, permission TEXT);
CREATE TABLE logins (person_id INTEGER PRIMARY KEY REFERENCES people(id) ON DELETE CASCADE, hashed_password TEXT, role_id INTEGER REFERENCES roles(id) ON DELETE CASCADE, reset_password BOOLEAN DEFAULT false, reset_token TEXT);
CREATE TABLE photos (guid TEXT PRIMARY KEY, filetype TEXT, bytes BYTEA);
CREATE TABLE notes (id SERIAL PRIMARY KEY, creator_id INTEGER REFERENCES people(id), created_time TIMESTAMP WITH TIME ZONE, edited BOOLEAN, private BOOLEAN, resource_type TEXT, resource_id INTEGER, note TEXT);
CREATE TABLE configuration (config TEXT PRIMARY KEY, value TEXT);
CREATE TABLE baptisms (id SERIAL PRIMARY KEY, name TEXT NOT NULL, person_id INTEGER, father_name TEXT, father_id INTEGER, mother_name TEXT, mother_id INTEGER, baptism_date DATE NOT NULL, baptism_location TEXT, birth_date DATE, birth_location TEXT, minister_name TEXT NOT NULL, minister_id INTEGER, godfather_name TEXT, godfather_id INTEGER, godmother_name TEXT, godmother_id INTEGER, witness_name TEXT, witness_id INTEGER, conditional BOOLEAN DEFAULT FALSE, reception BOOLEAN DEFAULT FALSE, notations TEXT);
